version: '3.4'

services:
  catalogdb:
    image: postgres:15
  userdb:
    image: postgres:15
  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catolog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  ticket.api:
    image: ${DOCKER_REGISTRY-}ticketapi
    build:
      context: .
      dockerfile: Services/Ticket/Ticket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_user: